# Use official nginx image as the base image
FROM public.ecr.aws/nginx/nginx:latest

# Copy the build output to replace the default nginx contents.
COPY dist/my-pets-chart /usr/share/nginx/html/app

# Expose port 80
EXPOSE 80